### ISSUE TITLE
Password Security

### ISSUE THREAD

**Issue by SenhasD** [1to5pc/python-auth#2]
Storing passwords as simple hashes without salting leaves them vulnerable to various attacks, such as dictionary attacks and rainbow table attacks. Consider adding a salt to enhance security.
Using a more secure hashing algorithm, such as bcrypt or Argon2, is recommended for password hashing.

**Comment by 1to5pc** [comment]
Implementation will take time, so sha256 for now. Added configuration option for hashing algorithms, though redundant for now.
